name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # astro build need node >= 22.12 apparently enven with bun
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Deps
        run: bun i --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Format Check
        run: bun prettier . --check

      - name: Build
        run: bun run build
