name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Deps
        run: bun i

      - name: Lint
        run: bun run lint

      - name: Format Check
        run: bun prettier . --check

      - name: Build
        run: bun run build
